
export const products = [
    {
        _id: '1',
        name: 'Taj Mahal Quartzite',
        category: 'Marble',
        image: '/images/TAJ-MAHAL.jpg',
        price: 7000,
        origin: 'Brazil',
        countInStock: 48,
    },
    {
        _id: '2',
        name: 'Potinary',
        category: 'Marble',
        image: '/images/portinari.jpg',
        price: 7000,
        origin: 'Brazil',
        countInStock: 76,
    },
    {
        _id: '3',
        name: 'Pitaya',
        category: 'Granite',
        image: '/images/PITAYA.jpg',
        price: 7000,
        origin: 'Brazil',
        countInStock: 12,
    },
    {
        _id: '4',
        name: 'Blue Deep',
        category: 'Marble',
        image: '/images/BLUE-DEEP.jpg',
        price: 7000,
        origin: 'Brazil',
        countInStock: 0,
    },
    {
        _id: '5',
        name: 'Black Mist Honed',
        category: 'Granite',
        image: '/images/Black-Mist-Honed.jpg',
        price: 7000,
        origin: 'Brazil',
        countInStock: 20,
    },
    {
        _id: '6',
        name: 'Platinum',
        category: 'Marble',
        image: '/images/PLATINUM.jpg',
        price: 7000,
        origin: 'Brazil',
        countInStock: 69,
    },
];
